version: "3.5"

services:
  frontend:
    image: ${FRONTEND_IMAGE_URL}:${IMAGE_TAG}
    ports:
      - 80:3000
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
