version: "3.5"

services:

  frontend-proxy:
    image: ${FRONTEND_PROXY_IMAGE_URL}:${IMAGE_TAG}
    depends_on:
      - radiomanager-frontend
      - radiomanager-backend
      - auth-server
      - audio-uploader
      - fileserver-local
    environment:
      VIRTUAL_HOST: "new.myownradio.biz"
      LETSENCRYPT_HOST: "new.myownradio.biz"
    networks:
      - default
      - global
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
    logging:
      driver: logentries
      options:
        logentries-token: 38e55397-cad8-4bb5-9e51-ba9e69275fbf
        line-only: "true"

  radiomanager-frontend:
    image: ${RADIOMANAGER_FRONTEND_IMAGE_URL}:${IMAGE_TAG}
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
    logging:
      driver: logentries
      options:
        logentries-token: ce50486e-28d5-4f5d-891f-c4579a502f47
        line-only: "true"

  radiomanager-backend:
    image: ${RADIOMANAGER_BACKEND_IMAGE_URL}:${IMAGE_TAG}
    environment:
      RADIOMANAGER_BACKEND_TOKEN_SECRET: me9IQW0atAzzE5nYKC6EiibAareI0to1
      RADIOMANAGER_BACKEND_METADATA_SECRET: kYzuRIRETBVZnyvDUrMT
      RADIOMANAGER_BACKEND_ALLOWED_ORIGIN: https://new.myownradio.biz
      RADIOMANAGER_BACKEND_DATABASE_URL: postgres://mor:mor@postgres:5432/mor
      RADIOMANAGER_BACKEND_DATABASE_CLIENT: postgresql
      RADIOMANAGER_BACKEND_METADATA_SIGNATURE_TTL: 30000
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
    logging:
      driver: logentries
      options:
        logentries-token: f430fefe-3ec2-4efb-8224-658baede7957
        line-only: "true"

  auth-server:
    image: ${AUTH_SERVER_IMAGE_URL}:${IMAGE_TAG}
    environment:
      AUTH_SERVER_TOKEN_SECRET: me9IQW0atAzzE5nYKC6EiibAareI0to1
      AUTH_SERVER_DATABASE_URL: postgres://mor:mor@postgres:5432/mor
      AUTH_SERVER_DATABASE_CLIENT: postgresql
      AUTH_SERVER_ACCESS_TOKEN_LIFETIME: 60
      AUTH_SERVER_REFRESH_TOKEN_LIFETIME: 604800 # one week
      AUTH_SERVER_ALLOWED_ORIGIN: https://new.myownradio.biz
    depends_on:
      - postgres
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    logging:
      driver: logentries
      options:
        logentries-token: db3ac942-eae5-4dc6-9e46-0a629f523b4d
        line-only: "true"

  fileserver-local:
    image: ${FILESERVER_LOCAL_IMAGE_URL}:${IMAGE_TAG}
    environment:
      FILESERVER_LOCAL_ROOT_FOLDER: /usr/content
      FILESERVER_LOCAL_TOKEN_SECRET: me9IQW0atAzzE5nYKC6EiibAareI0to1
      PORT: 8080
    volumes:
      - fileserver-local:/usr/content
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    logging:
      driver: logentries
      options:
        logentries-token: 2be455ac-d8c7-4592-bab3-12f74d3638ec
        line-only: "true"

  audio-uploader:
    image: ${AUDIO_UPLOADER_IMAGE_URL}:${IMAGE_TAG}
    environment:
      AUDIO_UPLOADER_ROOT_DIR: /usr/content
      AUDIO_UPLOADER_TOKEN_SECRET: me9IQW0atAzzE5nYKC6EiibAareI0to1
      AUDIO_UPLOADER_METADATA_SECRET: kYzuRIRETBVZnyvDUrMT
      AUDIO_UPLOADER_ALLOWED_ORIGIN: https://new.myownradio.biz
      PORT: 8080
    volumes:
      - audio-uploader:/usr/content
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
    logging:
      driver: logentries
      options:
        logentries-token: d4283584-5182-498d-a18f-7f6f0ab18a3d
        line-only: "true"

  # Migration
  migration:
    image: ${MIGRATION_IMAGE_URL}:latest
    command: npx knex migrate:latest
    environment:
      MIGRATION_DATABASE_URL: postgres://mor:mor@postgres:5432/mor
    depends_on:
      - postgres
    deploy:
      replicas: 1
      update_config:
        order: stop-first
      restart_policy:
        condition: on-failure
    logging:
      driver: logentries
      options:
        logentries-token: da274147-6e90-42a0-ba73-4c3660588904
        line-only: "true"

  # Backing Services
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: mor
      POSTGRES_PASSWORD: mor
      POSTGRES_DB: mor
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      update_config:
        order: stop-first
    logging:
      driver: logentries
      options:
        logentries-token: 0efaa5fb-80e7-43cb-aea5-94f59caf134f
        line-only: "true"

volumes:

  postgres:
    driver: local

  fileserver-local:
    driver: local

  audio-uploader:
    driver: local

networks:
  global:
    external: true
    name: global_default
