name: 'Deploy Single Application Service'

on:
  push:
    branches:
      - "radiomanager-frontend/*"

#  build-radiomanager-frontend:
#    needs: terraform
#    name: Build "radiomanager-frontend" image
#    runs-on: ubuntu-latest
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      SERVICE: radiomanager-frontend
#    steps:
#      - name: Checkout
#        uses: actions/checkout@master

jobs:
  init:
    name: Test image bump
    runs-on: ubuntu-latest
    steps:
      - name: Extract service name from ref
        id: service_name
        shell: bash
        run: |
          BRANCH_NAME=echo ${GITHUB_REF#refs/heads/}
          echo ${BRANCH_NAME}
          SERVICE_NAME=echo ${BRANCH_NAME%#/*}
          echo ${SERVICE_NAME}
#         echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#      - name: Checkout
#        uses: actions/checkout@master
#      - name: Build myownradio/radiomanager-frontend
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          registry: ${{ secrets.DOCKER_REGISTRY }}
#          repository: myownradio/radiomanager-frontend
#          path: app
#          dockerfile: app/services/radiomanager-frontend/Dockerfile
#          tags: ${{ github.sha }},latest
#      - name: Bump service image tag
#        uses: pldin601/patch-yaml-through-commit@master
#        with:
#          git_repo_url: https://pldin601:${{ secrets.GIT_PUSH_TOKEN }}@github.com/myownradio/myownradio-env.git
#          committer_name: Roman Lakhtadyr
#          committer_email: roman.lakhtadyr@gmail.com
#          commit_message: Update image to ${{ github.sha }}
#          yaml_file: swarm/docker-compose.yml
#          patch_expression: services.radiomanager-frontend.image=myregistry.com/radiomanager-frontend#${{ github.sha }}
#          dry_run: 1
