name: 'Deploy Single Application Service'

on:
  pull_request:
    types:
      - closed

jobs:
  main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    name: Deploy Single Application Service
    runs-on: ubuntu-latest
    steps:
      - name: Define variables
        id: variables
        shell: bash
        run: |
          STACK_NAME="myownradio"

          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          SERVICE_NAME=$(echo ${BRANCH_NAME%/*})
          BRANCH_SUFFIX_NAME=$(echo ${BRANCH_NAME#*/})

          IMAGE_NAME=$(echo ${STACK_NAME}/${SERVICE_NAME}:${{ github.sha }})
          IMAGE_URL=$(echo ${{ secrets.DOCKER_REGISTRY }}/${IMAGE_NAME})

          [ -z "$BRANCH_SUFFIX_NAME" ] && echo "Incorrent source service branch" && exit 1

          echo "##[set-output name=service_name;]$(echo ${SERVICE_NAME})"
          echo "##[set-output name=image_name;]$(echo ${IMAGE_NAME})"
          echo "##[set-output name=image_url;]$(echo ${IMAGE_URL})"
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Linter and Tests
        run: |
          make install
      - name: Run Linter
        run: make run-linter
      - name: Run Tests
        run: make run-tests
      - name: Build myownradio/${{ steps.variables.outputs.image_name }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: ${{ steps.variables.outputs.image_name }}
          path: app
          dockerfile: app/services/${{ steps.variables.outputs.service_name }}/Dockerfile
          tags: ${{ github.sha }},latest
      - name: Update environment repository
        uses: pldin601/patch-yaml-through-commit@master
        with:
          git_repo_url: https://pldin601:${{ secrets.GIT_PUSH_TOKEN }}@github.com/myownradio/myownradio-env.git
          committer_name: Roman Lakhtadyr
          committer_email: roman.lakhtadyr@gmail.com
          commit_message: Update image for ${{ steps.variables.outputs.service_name }}
          yaml_file: swarm/docker-compose.yml
          patch_expression: services.${{ steps.variables.outputs.service_name }}.image=${{ steps.variables.outputs.image_url }}
