name: 'Deploy Single Application Service'

on:
  push:
    branches:
      - "radiomanager-frontend/*"

jobs:
  init:
    name: Test image bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Extract service name from github_ref
        id: service_name
        shell: bash
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo ${BRANCH_NAME}
          SERVICE_NAME=$(echo ${BRANCH_NAME%/*})
          echo ${SERVICE_NAME}
          echo "##[set-output name=service_name;]$(echo ${SERVICE_NAME})"
      - name: Build myownradio/${{ steps.service_name.outputs.service_name }}#${{ github.sha }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          repository: myownradio/${{ steps.service_name.outputs.service_name }}
          path: app
          dockerfile: app/services/${{ steps.service_name.outputs.service_name }}/Dockerfile
          tags: ${{ github.sha }},latest
      - name: Update environment repository
        uses: pldin601/patch-yaml-through-commit@master
        with:
          git_repo_url: https://pldin601:${{ secrets.GIT_PUSH_TOKEN }}@github.com/myownradio/myownradio-env.git
          committer_name: Roman Lakhtadyr
          committer_email: roman.lakhtadyr@gmail.com
          commit_message: Update image to ${{ steps.service_name.outputs.service_name }}#${{ github.sha }}
          yaml_file: swarm/docker-compose.yml
          patch_expression: services.radiomanager-frontend.image=${{ secrets.DOCKER_REGISTRY }}/myownradio/${{ steps.service_name.outputs.service_name }}#${{ github.sha }}
          dry_run: 1
