name: 'Deploy'

on:
  push:
    branches: [ master ]

jobs:
  init:
    name: Run linter and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          sudo snap install terraform
          make setup-services
      - name: Linter
        run: make run-linter
      - name: Tests
        run: make run-tests

  terraform:
    needs: init
    name: Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      TF_VAR_insight_token: ${{ secrets.INSIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform'
      - name: Terraform Apply
        id: 'terraform'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: 'terraform'
      - name: Upload terraform artifacts
        uses: actions/upload-artifact@v1
        with:
          name: tf
          path: terraform/.terraform
  build:
    needs: terraform
    name: Build and push images
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      TF_VAR_insight_token: ${{ secrets.INSIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download terraform artifacts
        uses: actions/download-artifact@v1
        with:
          name: tf
          path: terraform/.terraform
      - name: Authenticate Docker on AWS
        run: aws ecr get-login --no-include-email --region eu-central-1 | sh
      - name: Build service images
        run: make build-all-services
      - name: Build application images
        run: make build-all-apps
      - name: Push images
        run: make push-all
  deploy:
    name: Deploy to Production
    needs: [ build, terraform ]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
      TF_VAR_insight_token: ${{ secrets.INSIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Checkout
        uses: actions/checkout@master
      - name: Download terraform artifacts
        uses: actions/download-artifact@v1
        with:
          name: tf
          path: terraform/.terraform
      - name: Gather terraform output
        id: terraform_output
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: 'terraform'
      - name: Parse terraform output
        id: parsed_output
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.terraform_output.outputs.tf_actions_output }}
          ssh_private_key: 'deployer_private_key.value'
          ssh_public_key: 'deployer_public_key.value'
          ip_address: 'mor_master_ip_address.value'

          # images here
          radiomanager_frontend_image: 'radiomanager-frontend_image_url.value'
          frontend_proxy_image: 'frontend-proxy_image_url.value'
          migration_image: 'migration_image_url.value'
          auth_server_image: 'auth-server_image_url.value'
          fileserver_local_image: 'fileserver-local_image_url.value'
          audio_uploader_image: 'audio-uploader_image_url.value'
          # end of images

          url: 'url.value'
      - name: Authenticate Remote Docker on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.parsed_output.outputs.ip_address }}
          username: deployer
          key: ${{ steps.parsed_output.outputs.ssh_private_key }}
          script: aws ecr get-login --region eu-central-1 --no-include-email | sh
      - name: Deploy stack to Production
        uses: pldin601/docker-swarm-deploy-action@master
        with:
          remote_host: ssh://deployer@${{ steps.parsed_output.outputs.ip_address }}
          ssh_private_key: ${{ steps.parsed_output.outputs.ssh_private_key }}
          ssh_public_key: ${{ steps.parsed_output.outputs.ssh_public_key }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          args: stack deploy --with-registry-auth --compose-file docker-compose.prod.yml mor
        env:
          # images here
          RADIOMANAGER_FRONTEND_IMAGE_URL: ${{ steps.parsed_output.outputs.radiomanager_frontend_image }}
          FRONTEND_PROXY_IMAGE_URL: ${{ steps.parsed_output.outputs.frontend_proxy_image }}
          MIGRATION_IMAGE_URL: ${{ steps.parsed_output.outputs.migration_image }}
          AUTH_SERVER_IMAGE_URL: ${{ steps.parsed_output.outputs.auth_server_image }}
          FILESERVER_LOCAL_IMAGE_URL: ${{ steps.parsed_output.outputs.fileserver_local_image }}
          AUDIO_UPLOADER_IMAGE_URL: ${{ steps.parsed_output.outputs.audio_uploader_image }}
          # end of images

          IMAGE_TAG: ${{ github.sha }}
      - name: Add comment to commit
        uses: peter-evans/commit-comment@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Successfully deployed to servers:
            - ${{ steps.parsed_output.outputs.ip_address }}

            URL:
            - ${{ steps.parsed_output.outputs.url }}
