name: 'Mirror to GitLab'

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror
        uses: wei/git-sync@v1
        env:
          SOURCE_REPO: ${{ github.repository }}
          SOURCE_BRANCH: main
          DESTINATION_REPO: git@gitlab.com:pldin601/myownradio-service.git
          DESTINATION_BRANCH: main
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
