name: Terraform

on:
  pull_request:
    types:
      - closed

jobs:
  init:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'refs/heads/master'
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
