name: Terraform

on:
  pull_request:
    types:
      - closed

jobs:
  init:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo OK
