name: Terraform

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  init:
    name: Foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
