name: Trigger Build
on:
  pull_request:
    types: [closed]
jobs:
  main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Define variables
        id: variables
        shell: bash
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          SERVICE_NAME=$(echo ${BRANCH_NAME%/*})
          echo "##[set-output name=service_name;]$(echo ${SERVICE_NAME})"
      - if: steps.variables.outputs.service_name == 'all'
        name: Build All Services
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_PUSH_TOKEN }}
          event-type: build-app-service
          client-payload: |
            {
              "services": [
                "radiomanager-frontend",
                "radiomanager-backend",
                "auth-server",
                "audio-uploader",
                "audio-player",
                "stream-composer"
              ],
              "tag": "${{ github.sha }}"
            }
      - if: steps.variables.outputs.service_name != 'all' && steps.variables.outputs.service_name != 'migration'
        name: Build One Service
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_PUSH_TOKEN }}
          event-type: build-app-service
          client-payload: |
            {
              "services": [
                "${{ steps.variables.outputs.service_name }}"
              ],
              "tag": "${{ github.sha }}"
            }
      - if: steps.variables.outputs.service_name == 'migration'
        name: Build Migration
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_PUSH_TOKEN }}
          event-type: build-app-service
          client-payload: |
            {
              "services": [
                "${{ steps.variables.outputs.service_name }}"
              ],
              "tag": "latest"
            }
